package Unit1;

public class ObjectCreationAndStorage {

	public static void main(String[] args) {
		
		/*
		 * An object is an instance of a class.
		 * 
		 * This means that objects are specific versions of complex
		 * data types. An object's properties/attributes and functions/methods
		 * are outlined in its class. Each object has the same types of 
		 * properties/attributes and can do the same actions, but each
		 * object is unique and has its own unique values for each of those
		 * properties/attributes.
		 * 
		 * In this way, using the analogy of baking cookies, classes are like
		 * the cookie cutters you may use. They are not cookies/objects themselves,
		 * but they define the form that the cookies/objects take. Likewise, the 
		 * actual cookies that go into the oven are like objects. Each one is slightly 
		 * different with differences in attributes (some may be M&M cookies, some may 
		 * be chocolate chip). However, they all take the same shape as outlined by 
		 * their cookie cutter or class.
		 * 
		 * The Card class defines 4 properties/attributes:
		 * -String suit
		 * -int value
		 * -String label
		 * -boolean hidden
		 * 
		 * Each Card object has several functions/methods/actions. Some of these include:
		 * -flip
		 * -getValue
		 * -setValue
		 */
		
		//creating objects from classes is called instantiation
		
		/*
		 * Creates a Card object named 'card1' with the Card class' 
		 * two-parameter constructor. 
		 * 
		 * This one is a 5 of hearts
		 */
		Card card1 = new Card(5, "Hearts");
		
		/*
		 * Creates a Card object with random values generated by the 
		 * Card class' no-parameter constructor
		 */
		Card card2 = new Card();
		
		//Card objects are face down by default, as if they were just dealt
		System.out.println("Card1:\n" + card1);
		System.out.println("Card2:\n" + card2);
		
		//flips card1 over
		card1.flip();
		System.out.println("Card1:\n" + card1);
		
		//card2 is still face down
		System.out.println("Card2:\n" + card2);
		
		//but we can still check its value
		System.out.println("Value of card 2: " + card2.getValue());
		
		//flipping card2 to verify value
		card2.flip();
		System.out.println("Card2:\n" + card2);
		
	}

}
